<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="<?php echo base_url('assets/client/') ?>/surat/style1.css" />
    <title>Laporan Hasil Laporan Diagnosa </title>
  </head>
   <body>

	<div class="book">
		<div class="page">
			<div class="subpage">
				<div class="content">
					<div style="width:128mm;float:left;">
						HealthMe.
					</div>
					<div style="width:128mm;float:right;">
						<p style="text-align:right;"></button>&nbsp;&nbsp;&nbsp;<button style="text-align:right;" onclick="window.print()">Print</button></p>
						<p style="text-align:right;">Generated By System : <?php echo date('Y-m-d h:i:s');?> </p>
					</div>
					<div style="clear:both;"></div>
					<hr/>
					<center>
						<h1 style="font-weight:none;font-size:28pt">HealthMe.</h1>
						<h2>Pengelolaan Pola Hidup Sehat Pada Remaja</h2>

						</center>
					<hr/>

					<div style="clear:both;"></div>

					<center>
						&nbsp;&nbsp;
						<p style="font-weight:none;font-size:16pt">HASIL LAPORAN DIAGNOSA </p>
					</center>

					</div>
                    <table class="tb1" style="width: 100%;height:70px;" border="1">
						<thead>
							<th>No</th>

							<th  style="text-align:center;">Nama Penyakit</th>
							<th  style="text-align:center;">Jumlah Penderita</th>

						</thead>

						<?php
                        $no = 0 ;

                        foreach($listData as $value){

                        $no++;
                         $get = $this->db->query("SELECT COUNT(*) as total FROM detailhasilanalisa WHERE penyakit LIKE '%".$value->penyakit."%'")->row()->total;

						?>
						<tr class="isi-colom">
							 <td  style="font-size:10pt;"><?php echo $no; ?></td>
							 <td  style="font-size:10pt;">&nbsp;<?php echo $value->penyakit ?></td>
							 <td  style="font-size:10pt;">&nbsp;<?php echo $get ?></td>


						</tr>
                        <?php
						}  ?>

					</table>



				</div>
			</div>
		</div>
	</div>

   </body>
</html>
</html>
